### ISSUE TITLE
Isn't working on demopage

### ISSUE THREAD

**Issue by do7be** [chenglou/react-tween-state#64]
I tried access this library's demopage. But didn't work :(

https://rawgit.com/chenglou/react-tween-state/master/examples/index.html

**Comment by zivanovicb** [comment]
`
Uncaught Error: Cannot find module "./index.js"
    at https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8477
    at Object.<anonymous> (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8522)
    at t (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8349)
    at https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8436
    at https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8441
    at n.(anonymous function).exports (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8214)
    at Object.<anonymous> (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:21:8218)
    at t (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:1:330)
    at Object.e.__esModule.default (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:22:5456)
    at t (https://rawgit.com/chenglou/react-tween-state/master/examples/index.js:1:330)
`
